# Generated by Django 6.0.7 on 2026-07-25 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entity was last updated')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_hours_used', models.FloatField(default=0.0)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('estimated_duration_hours', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entity was last updated')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entity was last updated')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'db_table': 'otp_verifications',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entity was last updated')),
                ('location', models.CharField(max_length=255)),
                ('stop_type', models.CharField(choices=[('CURRENT', 'Current Location'), ('PICKUP', 'Pickup Location'), ('DROPOFF', 'Dropoff Location'), ('REST_BREAK', '30-Minute Rest Break'), ('SLEEPER', '10-Hour Sleeper Berth'), ('FUEL', 'Fuel Stop')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('duration_hours', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, default='')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='models.trip')),
            ],
            options={
                'db_table': 'trip_stops',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entity was last updated')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('off_duty_hours', models.FloatField(default=10.0)),
                ('sleeper_berth_hours', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=11.0)),
                ('on_duty_not_driving_hours', models.FloatField(default=3.0)),
                ('total_miles_driven', models.FloatField(default=500.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='models.trip')),
            ],
            options={
                'db_table': 'daily_logs',
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
