"""
FMCSA Hours of Service (HOS) regulatory constants.
"""

MAX_DRIVING_HOURS_PER_DAY = 11.0
MAX_DUTY_HOURS_PER_DAY = 14.0
MANDATORY_REST_BREAK_THRESHOLD = 8.0
MANDATORY_REST_BREAK_DURATION = 0.5  # 30 minutes
MANDATORY_SLEEPER_DURATION = 10.0     # 10 hours
MAX_CYCLE_HOURS_70_8 = 70.0
MILES_PER_FUEL_STOP = 1000.0
AVERAGE_SPEED_MPH = 55.0
